# Generated by Django 6.0 on 2026-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('story', models.TextField()),
                ('region', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
