# Generated by Django 6.0 on 2026-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(db_index=True, default='legacy', max_length=40),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
    ]
