# Generated by Django 6.0 on 2026-01-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_unique_together_cart_session_key_and_more'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('session_key', 'product')},
        ),
    ]
